import i18n from "i18next";
import { initReactI18next } from "react-i18next";

const zh={translation:{
  appTitle:"圆弧底扫描器",appSubtitle:"本地多周期技术状态台",configured:"LongPort 已配置",notConfigured:"LongPort 未配置",securities:"只证券",scan:"同步并扫描",scanning:"正在创建…",watchlistScore:"股票池与评分",search:"搜索代码",minimum:"最低分",unlimited:"不限",roundBottom:"圆弧底",multiPeriod:"多周期",waitingFactors:"等待因子结果",normal:"正常",waitingScan:"等待扫描",connecting:"正在连接本地服务…",loadedLatest:"已载入最近一次正式扫描",noOfficialResults:"尚无正式扫描结果",scanStarted:"扫描任务已创建（{{id}}）",scanProgress:"扫描中：成功 {{succeeded}} / {{total}}，失败 {{failed}}",scanComplete:"扫描完成：{{succeeded}} 只证券",scanEnded:"扫描结束：成功 {{succeeded}}，失败 {{failed}}",watchlistSaved:"股票池已保存：{{count}} 只证券",
  "tab.chart":"图表与分析","tab.diagnostics":"因子诊断","tab.scoring":"评分详情","tab.history":"历史表现","tab.data":"数据管理","tab.watchlist":"股票池管理","tab.settings":"系统设置",
  language:"语言",loading:"正在读取本地数据…",selectStock:"请从左侧选择股票",weekly:"周线",daily:"日线",fourHour:"4 小时",triggered:"触发",notTriggered:"未触发",none:"无",factor:"因子",status:"状态",factorContribution:"因子贡献",resonance:"周期共振",beforeMultiplier:"乘数前",fullCoverage:"全覆盖",finalScore:"最终评分",baseScore:"基础分",crossMultiplier:"跨周期倍数",contribution:"贡献",noHistory:"尚无历史正式扫描",highest:"最高",authoritative:"LongPort 权威源",barCount:"K 线数量",earliest:"最早时间",latest:"最新时间",lastSync:"最后同步",noCache:"该股票尚无本地缓存",
  analysisSummary:"分析摘要",score:"综合评分",triggeredFactors:"触发因子",coverage:"全覆盖倍数",multiFactors:"多周期因子",periodSummary:"周期概况",noFactors:"没有触发因子",observation:"辅助观察",observationText:"趋势线和 MACD 已显示在图表中，目前不参与评分。",
  watchlistManager:"股票池管理",watchlistHelp:"每行一个美股代码，无需填写 .US。也可使用空格或逗号分隔；其他市场请保留后缀，例如 700.HK。",importTxt:"从 TXT 导入",saveWatchlist:"保存股票池",saving:"正在保存…",autoBackfill:"自动补全已启用",autoBackfillText:"点击顶部“同步并扫描”后，没有本地缓存的新增股票将分别下载完整历史 K 线；已有股票只做增量同步。",importHint:"导入会合并到编辑区；确认后保存，不会立即请求行情。",
  forward:"前复权",allSessions:"全交易时段",localCache:"本地缓存",bars:"根",trendSupport:"趋势支撑",trendResistance:"趋势压力",macdNote:"MACD 12/26/9 · 不参与评分",chartLoading:"正在从本地缓存载入…",chartError:"无法显示图表",syncFirst:"请先完成该股票的行情同步。",bottomDiagnosis:"底部形成诊断",bottomExtended:"上涨延伸",bottomUptrend:"上涨趋势·远离底部",bottomBreakout:"突破启动",bottomConfirmed:"底部已确认",bottomForming:"底部构筑中",insufficient:"数据不足",notFormed:"尚未形成",diagnosisNote:"解释性组合判断，不参与当前评分",noBottomEvidence:"尚未出现圆弧底或 F1/F2 早期组合",insufficientBottom:"各周期圆弧底历史均不足"
  ,systemSettings:"系统设置",settingsConfigured:"已配置",settingsNotConfigured:"未配置",authMethod:"LongPort 认证方式",oauthRecommended:"OAuth 2.0（推荐）",oauthDescription:"首次浏览器授权，Token 由 SDK 持久化并自动刷新。",apiKeyMethod:"传统 API Key",apiKeyDescription:"使用 .env 中的 App Key、App Secret 和 Access Token。",saveAuth:"保存认证设置",processing:"处理中…",authorizeOAuth:"立即进行 OAuth 授权",authSaved:"认证设置已保存并应用",saveFailed:"保存失败",waitingAuthorization:"正在等待浏览器授权…",oauthSuccess:"OAuth 授权成功，Token 将由 LongPort SDK 自动管理",oauthFailed:"OAuth 授权失败",networkProxy:"网络代理",proxyDescription:"用于 LongPort SDK 的行情请求和认证通信。",enabled:"已启用",disabled:"未启用",proxyHost:"代理主机",proxyPort:"代理端口",currentProxy:"当前代理地址：{{url}}",saveProxy:"保存代理设置",proxyEnabledMessage:"网络代理已启用：{{url}}",proxyDisabledMessage:"网络代理已关闭",proxySaveFailed:"代理设置保存失败",proxyBrowserNote:"OAuth 授权网页由默认浏览器打开，仍使用 Windows 或浏览器自身的代理设置；本地回调 127.0.0.1 不经过代理。",securityNote:"安全说明",securityText:"OAuth Token 不会显示在界面中，默认存放于 Windows 用户目录的 .longport/openapi/tokens。切换到 API Key 模式不会删除已有 OAuth Token。",evidenceRoundBottom:"{{timeframe}}圆弧底",evidenceRiseFromBottom:"{{timeframe}}距拟合底部上涨 {{value}}%",evidenceBreakoutStage:"{{timeframe}}进入突破阶段",evidenceConfirmation:"{{timeframe}}确认 {{factors}}",evidenceFarFromTunnel:"{{timeframe}}已远离均线通道 {{value}}%",evidenceLeftBottomTunnel:"{{timeframe}}已脱离底部通道",evidenceEarlyCombination:"{{timeframe}} F1/F2 早期组合",evidenceAboveLongTunnel:"{{timeframe}}价格高于长期通道 {{value}}%",evidenceSeparator:"；"
}};
const en={translation:{
  appTitle:"Round Bottom Scanner",appSubtitle:"Local Multi-Timeframe Technical Dashboard",configured:"LongPort Connected",notConfigured:"LongPort Not Connected",securities:"securities",scan:"Sync & Scan",scanning:"Starting…",watchlistScore:"Watchlist & Scores",search:"Search symbol",minimum:"Min score",unlimited:"All",roundBottom:"Round Bottom",multiPeriod:"Multi-Timeframe",waitingFactors:"Waiting for factor results",normal:"Normal",waitingScan:"Waiting for Scan",connecting:"Connecting to local service…",loadedLatest:"Latest official scan loaded",noOfficialResults:"No official scan results",scanStarted:"Scan task created ({{id}})",scanProgress:"Scanning: {{succeeded}} / {{total}} succeeded, {{failed}} failed",scanComplete:"Scan complete: {{succeeded}} securities",scanEnded:"Scan ended: {{succeeded}} succeeded, {{failed}} failed",watchlistSaved:"Watchlist saved: {{count}} securities",
  "tab.chart":"Charts & Analysis","tab.diagnostics":"Factor Diagnostics","tab.scoring":"Score Details","tab.history":"History","tab.data":"Data Management","tab.watchlist":"Watchlist Manager","tab.settings":"System Settings",
  language:"Language",loading:"Loading local data…",selectStock:"Select a stock from the left",weekly:"Weekly",daily:"Daily",fourHour:"4 Hours",triggered:"Triggered",notTriggered:"Not Triggered",none:"None",factor:"Factor",status:"Status",factorContribution:"Factor Contribution",resonance:"Timeframe Confluence",beforeMultiplier:"Before Multiplier",fullCoverage:"Full Coverage",finalScore:"Final Score",baseScore:"Base Score",crossMultiplier:"Cross-Timeframe Multiplier",contribution:"Contribution",noHistory:"No Official Scan History",highest:"Highest",authoritative:"LongPort Authoritative Source",barCount:"Bars",earliest:"Earliest",latest:"Latest",lastSync:"Last Sync",noCache:"No Local Cache for This Stock",
  analysisSummary:"Analysis Summary",score:"Total Score",triggeredFactors:"Triggered Factors",coverage:"Coverage Multiplier",multiFactors:"Multi-Timeframe Factors",periodSummary:"Timeframe Summary",noFactors:"No factors triggered",observation:"Observation",observationText:"Trendlines and MACD are displayed on the chart and do not affect scoring.",
  watchlistManager:"Watchlist Manager",watchlistHelp:"Enter one US symbol per line without .US. Spaces and commas are also supported; keep suffixes for other markets, e.g. 700.HK.",importTxt:"Import TXT",saveWatchlist:"Save Watchlist",saving:"Saving…",autoBackfill:"Auto Backfill Enabled",autoBackfillText:"After Sync & Scan, new symbols without local cache download full history; existing symbols use incremental updates.",importHint:"Imported symbols are merged into the editor. Review and save; importing does not request market data.",
  forward:"Forward Adjusted",allSessions:"All Sessions",localCache:"Local Cache",bars:"bars",trendSupport:"Trend Support",trendResistance:"Trend Resistance",macdNote:"MACD 12/26/9 · Not Scored",chartLoading:"Loading from local cache…",chartError:"Unable to Display Chart",syncFirst:"Sync market data for this stock first.",bottomDiagnosis:"Bottom Formation Diagnosis",bottomExtended:"Uptrend Extension",bottomUptrend:"Uptrend · Far From Bottom",bottomBreakout:"Breakout",bottomConfirmed:"Bottom Confirmed",bottomForming:"Bottom Forming",insufficient:"Insufficient Data",notFormed:"Not Formed",diagnosisNote:"Explanatory diagnosis; does not affect scoring",noBottomEvidence:"No round bottom or early F1/F2 combination",insufficientBottom:"Insufficient round-bottom history across timeframes"
  ,systemSettings:"System Settings",settingsConfigured:"Configured",settingsNotConfigured:"Not Configured",authMethod:"LongPort Authentication",oauthRecommended:"OAuth 2.0 (Recommended)",oauthDescription:"Authorize once in your browser. The SDK stores and refreshes the token automatically.",apiKeyMethod:"API Key",apiKeyDescription:"Use the App Key, App Secret, and Access Token stored in .env.",saveAuth:"Save Authentication",processing:"Processing…",authorizeOAuth:"Authorize with OAuth",authSaved:"Authentication settings saved and applied",saveFailed:"Unable to save settings",waitingAuthorization:"Waiting for browser authorization…",oauthSuccess:"OAuth authorization succeeded. The LongPort SDK will manage the token.",oauthFailed:"OAuth authorization failed",networkProxy:"Network Proxy",proxyDescription:"Used by the LongPort SDK for market-data and authentication requests.",enabled:"Enabled",disabled:"Disabled",proxyHost:"Proxy Host",proxyPort:"Proxy Port",currentProxy:"Current proxy: {{url}}",saveProxy:"Save Proxy Settings",proxyEnabledMessage:"Network proxy enabled: {{url}}",proxyDisabledMessage:"Network proxy disabled",proxySaveFailed:"Unable to save proxy settings",proxyBrowserNote:"The OAuth page opens in your default browser and follows the Windows or browser proxy settings. The local 127.0.0.1 callback bypasses the proxy.",securityNote:"Security",securityText:"OAuth tokens are never displayed here. By default, they are stored under .longport/openapi/tokens in your Windows user directory. Switching to API Key does not delete an existing OAuth token.",evidenceRoundBottom:"{{timeframe}} round bottom",evidenceRiseFromBottom:"{{timeframe}} rose {{value}}% from the fitted bottom",evidenceBreakoutStage:"{{timeframe}} entered the breakout stage",evidenceConfirmation:"{{timeframe}} confirmed by {{factors}}",evidenceFarFromTunnel:"{{timeframe}} is {{value}}% above the EMA tunnel",evidenceLeftBottomTunnel:"{{timeframe}} has left the bottom channel",evidenceEarlyCombination:"{{timeframe}} early F1/F2 combination",evidenceAboveLongTunnel:"{{timeframe}} price is {{value}}% above the long-term tunnel",evidenceSeparator:"; "
}};
const saved=localStorage.getItem("scanner-language");
const initial=saved??(navigator.language.toLowerCase().startsWith("zh")?"zh-CN":"en-US");
void i18n.use(initReactI18next).init({resources:{"zh-CN":zh,"en-US":en},lng:initial,fallbackLng:"zh-CN",interpolation:{escapeValue:false}});
export function setLanguage(language:"zh-CN"|"en-US"){localStorage.setItem("scanner-language",language);void i18n.changeLanguage(language)}
export default i18n;
